### ISSUE TITLE
Error occurred while adding textures

### ISSUE THREAD

**Issue by justMan2440** [passivestar/substance-tools#11]
Error occurred while adding textures: Operator bpy.ops.node.nw_add_textures_for_principled.poll() No active node.
Traceback (most recent call last):
  File "C:\Users\serse\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\substance-tools\__init__.py", line 309, in execute
    bpy.ops.node.nw_add_textures_for_principled(directory=directory, files=files)
  File "F:\SteamLibrary\steamapps\common\Blender\4.2\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Operator bpy.ops.node.nw_add_textures_for_principled.poll() No active node.

![изображение_2024-11-09_000656210](https://github.com/user-attachments/assets/9fcb2b6f-a589-46d2-b4c4-d900279b3a0b)

**Comment by justMan2440** [comment]
I click load and nothing happens
